// vue-client/src/views/cars/CarsList.vue
<template>
  <div class="columns m-6">
    <router-link to="/cars/create">Create</router-link>
  </div>
  <div class="column is-10-desktop m-6">
    <table class="table">
      <thead>
      <tr>
        <th>Id</th>
        <th>Type Id</th>
        <th>User Id</th>
        <th>Created By</th>
        <th>Created At</th>
        <th>Updated By</th>
        <th>Updated At</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>Id</th>
        <th>Type Id</th>
        <th>User Id</th>
        <th>Created By</th>
        <th>Created At</th>
        <th>Updated By</th>
        <th>Updated At</th>
      </tr>
      </tfoot>
      <tbody>
      <tr v-for="car of cars" :key="car.id">
        <th><router-link :to="'/cars/' + car.id">{{car.id}}</router-link></th>
        <td>{{car.carTypeId}}</td>
        <td>{{car.appUserId}}</td>
        <td>{{car.createdBy}}</td>
        <td>{{car.createdAt}}</td>
        <td>{{car.updatedBy}}</td>
        <td>{{car.updatedAt}}</td>
      </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component'
import { CarsService } from '@/services/cars-service'
import { ICar } from '@/models/ICar'

export default class CarsList extends Vue {
  service: CarsService | null = null
  cars: ICar[] = []

  async mounted (): Promise<void> {
    this.service = new CarsService()
    await this.service.getAll()
      .then(res => {
        if (res.data !== undefined) {
          console.log(res.data)
          this.cars = res.data!
        } else {
          console.error(res.errorMessage)
        }
      })
  }
}
</script>

<style scoped>

</style>

// react-client/src/views/cars/CarsList.tsx
import {NavLink} from "react-router-dom";
import {ICar} from "../../types/ICar";
import {useEffect, useState} from "react";
import Loader from "../../components/Loader";
import {EPageStatus} from "../../types/EPageStatus";
import {CarsService} from "../../services/cars-service";

const CarsList = () => {
    const [cars, setCars] = useState([] as ICar[]);
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const service = new CarsService();

    const loadData = async () => {
        let result = await service.getAll();

        if (result.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setCars(result.data!);
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: result.statusCode });
        }
    }

    useEffect(() => {
        loadData();
    }, []);


    return (
        <>
            <div className="columns m-6">
                <NavLink to="/cars/create">Create</NavLink>
            </div>
            <div className="column is-10-desktop m-6">
                <table className="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Type</th>
                        <th>User</th>
                        <th>Created By</th>
                        <th>Created At</th>
                        <th>Updated By</th>
                        <th>Updated At</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Type</th>
                        <th>User</th>
                        <th>Created By</th>
                        <th>Created At</th>
                        <th>Updated By</th>
                        <th>Updated At</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {
                        cars.map((car) =>
                            <tr key={car.id}>
                                <th><NavLink to={'/cars/' + car.id}>{car.id}</NavLink></th>
                                <td>{car.carType?.name}</td>
                                <td>{car.appUser?.displayName}</td>
                                <td>{car.createdBy}</td>
                                <td>{car.createdAt}</td>
                                <td>{car.updatedBy}</td>
                                <td>{car.updatedAt}</td>
                            </tr>
                        )
                    }
                    </tbody>
                </table>
            </div>
            <Loader {...pageStatus} />
        </>
    )
}

export default CarsList;
