// react-client/src/views/cars/CarCreate.tsx
import {NavLink, useParams} from "react-router-dom";
import {ICarType} from "../../types/ICarType";
import {ICar} from "../../types/ICar";
import {useEffect, useState} from "react";
import {CarsService} from "../../services/cars-service";
import {CarTypeService} from "../../services/car-type-service";

const CarCreate = () => {
    const [car, setCar] = useState({carTypeId: ''} as ICar);
    const [carTypes, setCarTypes] = useState([] as ICarType[]);
    const service = new CarsService();
    const carTypesService = new CarTypeService();

    console.log(1)

    useEffect(() => {
        carTypesService.getAll().then(res => {
            if (res.data) {
                setCarTypes(res.data);
            }
        })
        console.log(3)

    }, [])

    const onClickSave = () => {
        service.post(car!).then((res) => {
            if (res.data) {
                window.location.href = `/cars/${res.data.id}`;
            }
        })
    }

    console.log(2)

    return (
        <div className="container">
            <h1>Create new car</h1>
            <div className="column">
                <hr/>
                <div className="column">
                    <div className="columns">
                        <div className="column is-4-desktop">
                            Type
                        </div>
                        {
                            <select onChange={(e) => setCar({...car, carTypeId: e.target.value})}
                                    className="column is-8-desktop">
                                {carTypes.map((type) =>
                                    <option value={type.id} key={type.id}>
                                        {type.carModel?.carMark?.name} - {type.carModel?.name} - {type.name}
                                    </option>
                                )
                                }
                            </select>
                        }
                    </div>
                </div>
            </div>
            <div>
                {
                    <button className="button m-2 is-success" onClick={onClickSave}>Create</button>
                }
                <NavLink className="button m-2" to="/cars">Back to List</NavLink>
            </div>
        </div>
    )
}

export default CarCreate;

// vue-client/src/views/cars/CarCreate.vue
<template>
  <div class="container">
    <h1>Create Car</h1>

    <div class="column">
      <hr/>
      <div class="column">
        <div class="columns">
          <div class="column is-4-desktop">
            Type
          </div>
          <select v-model="car.carTypeId" class="column is-8-desktop">
            <option v-for="type of carTypes" :value="type.id" :key="type.id">
              {{type.carModel.carMark.name}} - {{type.carModel.name}} - {{type.name}}
            </option>
          </select>
        </div>
      </div>
    </div>
    <div>
      <button class="button m-2 is-primary" @click="onClickCreate">Create</button>
      <router-link class="button m-2" to="/cars">Back</router-link>
    </div>
  </div>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component'
import { ICar, INewCar } from '@/models/ICar'
import { ICarType } from '@/models/ICarType'
import { CarsService } from '@/services/cars-service'
import { CarTypeService } from '@/services/car-type-service'

export default class CarCreate extends Vue {
  car: INewCar = {
    carTypeId: ''
  }

  carTypes: ICarType[] = []
  service: CarsService | null = null
  carTypeService: CarTypeService | null = null

  mounted (): void {
    this.service = new CarsService()
    this.carTypeService = new CarTypeService()
    this.carTypeService.getAll()
      .then(res => {
        if (res.data !== undefined) {
          this.carTypes = res.data
        } else {
          console.log(res.errorMessage)
        }
      })
  }

  async onClickCreate (): Promise<void> {
    const res = await this.service?.post(this.car as ICar)
    console.info(res)
    await this.$router.push('/cars')
  }
}
</script>

<style scoped>

</style>
