// react-client/src/components/Header.tsx
import {NavLink} from "react-router-dom";
import getCookie from "../utils/getCookie";

const Header = () => {
    const onLogOutClicked = () => {
        localStorage.removeItem('token')
        document.cookie.split(";").forEach(function(c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });
        window.location.href = '/'
    }

    const jwt = getCookie('jwt');

    return (
        <header>
            <nav className="navbar" role="navigation" aria-label="main navigation">
                <div className="navbar-brand">
                    <a className="navbar-item" href="https://bulma.io">
                        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"/> </a>

                    <a role="button" className="navbar-burger" aria-label="menu" aria-expanded="false"
                       data-target="navbarBasicExample">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>

                <div id="navbarBasicExample" className="navbar-menu">
                    <div className="navbar-start">
                        {jwt && <NavLink to="/cars" className="navbar-item">Cars</NavLink>}
                        {jwt && <NavLink to="/errors" className="navbar-item">Errors</NavLink>}
                        {jwt && <NavLink to="/accesses" className="navbar-item">Accesses</NavLink>}
                        <NavLink to="/marks" className="navbar-item">Marks</NavLink>
                        <NavLink to="/models" className="navbar-item">Models</NavLink>
                        <NavLink to="/types" className="navbar-item">Types</NavLink>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className="navbar-item">
                        <div className="buttons">
                            {(jwt || '') === ''
                                ? <>
                                    <a className="button is-primary" href="/register">
                                        <strong>Sign up</strong>
                                    </a>
                                    <a className="button is-light" href="/login">
                                        Log in
                                    </a>
                                </>
                                :
                                <button className="button is-light" onClick={onLogOutClicked}>
                                    Log out
                                </button>
                            }
                        </div>
                    </div>
                </div>
            </nav>
        </header>
    )
}

export default Header;

// exam/src/components/Header.vue
<template>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <!--        <router-link v-if="token" to="/cars" class="navbar-item">CarsList</router-link>-->
        <!--        <router-link to="/marks" class="navbar-item">Marks</router-link>-->
        <!--        <router-link to="/models" class="navbar-item">Models</router-link>-->
        <!--        <router-link to="/types" class="navbar-item">Types</router-link>-->
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a v-if="!token" class="button is-primary" href="/register">
            <strong>Sign up</strong>
          </a>
          <a v-if="!token" class="button is-light" href="/login">
            Log in
          </a>
          <button v-if="token" class="button is-light" @click="onLogOutClicked">
            Log out
          </button>
        </div>
      </div>
    </div>
  </nav>

</template>

<script lang="ts">
import {Vue} from 'vue-class-component'
import store from '@/store/index'

export default class Header extends Vue {
  get token() {
    return store.state?.token !== null && store.state.token.length > 1
  }

  async onLogOutClicked() {
    store.commit('logOut')
  }
}
</script>

<style scoped>

</style>
