// react-client/src/views/models/ModelsList.tsx
import {useEffect, useState} from "react";
import {EPageStatus} from "../../types/EPageStatus";
import {NavLink} from "react-router-dom";
import isAdmin from "../../utils/isAdmin";
import {ICarModel} from "../../types/ICarModel";
import {CarModelService} from "../../services/car-model-service";


const ModelsList = () => {
    const [models, setModels] = useState([] as ICarModel[]);
    const [pageStatus, setPageStatus] = useState({pageStatus: EPageStatus.Loading, statusCode: -1});
    const service = new CarModelService();

    const loadData = async () => {
        let result = await service.getAll();

        if (result.data) {
            setPageStatus({pageStatus: EPageStatus.OK, statusCode: 0});
            setModels(result.data!);
        } else {
            setPageStatus({pageStatus: EPageStatus.Error, statusCode: result.statusCode});
        }
    }

    const admin = isAdmin();

    useEffect(() => {
        loadData();
    }, []);

    return (
        <>
            <div className="columns m-6">
                {admin &&
                <NavLink to="/models/create">Create</NavLink>
                }
            </div>
            <div className="column is-10-desktop m-6">
                <table className="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Model</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Model</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {
                        models.map((model) =>
                            <tr key={model.id}>
                                <th><NavLink to={'/models/' + model.id}>{model.id}</NavLink></th>
                                <td>{model.name}</td>
                                <td>{model.carMark?.name}</td>
                                <td>{model.createdAt}</td>
                                <td>{model.updatedAt}</td>
                            </tr>
                        )
                    }
                    </tbody>
                </table>
            </div>
        </>
    )
}

export default ModelsList;

// vue-client/src/views/models/ModelsList.vue
<template>
  <div class="columns m-6">
    <router-link v-if="isAdmin" to="/models/create">Create</router-link>
  </div>
  <div class="column is-10-desktop m-6">
    <table class="table">
      <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Model</th>
        <th>Created By</th>
        <th>Created At</th>
        <th>Updated By</th>
        <th>Updated At</th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Mark</th>
        <th>Created By</th>
        <th>Created At</th>
        <th>Updated By</th>
        <th>Updated At</th>
      </tr>
      </tfoot>
      <tbody>
      <tr v-for="model of models" :key="model.id">
        <th><router-link :to="'/models/' + model.id">{{model.id}}</router-link></th>
        <td>{{model.name}}</td>
        <td>{{model.carMark?.name}}</td>
        <td>{{model.createdBy}}</td>
        <td>{{model.createdAt}}</td>
        <td>{{model.updatedBy}}</td>
        <td>{{model.updatedAt}}</td>
      </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component'
import { ICarType } from '@/models/ICarType'
import { CarTypeService } from '@/services/car-type-service'
import { CarModelService } from '@/services/car-model-service'
import { ICarModel } from '@/models/ICarModel'
import store from '@/store'
import { getParsedJwt } from '@/util/jwt'
import { IJwt } from '@/models/IJwt'

export default class ModelsList extends Vue {
  service: CarModelService | null = null
  models: ICarModel[] = []

  async mounted (): Promise<void> {
    this.service = new CarModelService()
    await this.service.getAll()
      .then(res => {
        if (res.data !== undefined) {
          console.log(res.data)
          this.models = res.data!
        } else {
          console.error(res.errorMessage)
        }
      })
  }

  get isAdmin () {
    return store.state?.token !== null && (getParsedJwt<IJwt>(store.state!.token!)?.
      ['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']?.includes('Admin') || false)
  }
}
</script>

<style scoped>

</style>
